name: Update README

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/org/example/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List files in src directory
        run: |
          echo "Current directory structure:"
          ls -R src/main/java/org/example/

      - name: Update README
        run: |
          python .github/scripts/update_readme.py

      - name: Show git status
        run: |
          git status

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --cached --quiet || (git commit -m "Update README.md [skip ci]" && git push)