name: Update README

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/java/org/example/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List files in src directory
        run: |
          echo "Current directory structure:"
          ls -R src/main/java/org/example/

      - name: Debug environment
        run: |
          pwd
          ls -la
          python --version

      - name: Update README
        run: |
          python -u .github/scripts/update_readme.py

      - name: Check README content
        run: |
          echo "Checking if README.md exists:"
          ls -l README.md || echo "README.md not found"
          echo "Content of README.md:"
          cat README.md || echo "Cannot read README.md"

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          echo "Git status before add:"
          git status
          git add README.md
          echo "Git status after add:"
          git status
          git diff --cached
          git diff --cached --quiet || (git commit -m "Update README.md [skip ci]" && git push)